version: "3.9"  # optional since v1.2.something
services:
  web:
    image: nginx:latest
    ports:
     - "8080:80"
    links:
     - php
  php:
    image: php:7-fpm
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=claim-vNC3tx_VqpsRsPsScK8y
      - ADVERTISE_IP=http://10.0.0.147:32400/
    hostname: plexserver.example.com
    volumes:
      - ${USERDIR}/docker/plexms:/config
      - ${USERDIR}/Downloads/plex_tmp:/transcode
      - /home/patrick/Downloads:/media
      - ${USERDIR}/docker/shared:/shared
